def Gangnam_Style
  puts "Lower Body"
  puts "Assume the proper stance"
  puts "1. Plant legs far apart, bend knees slightly and keep posture loose"
  puts "Base Footwork"
  puts "1. Lift right foot"
  puts "2. Return right foot to the ground"
  puts "3. Finishing with a small skip-stop backward"
  
  puts "Skip Step"
  puts "Skip Step Left"
  puts "1. Lower left foot to the ground"
  puts "2. Bounce left foot back up slightly, kicking it a few inches back"
  puts "3. Left, Right, Left and Left"
  puts "Skip Step Right"
  puts "1. Lower right foot to the ground"
  puts "2. Bounce right foot back up slightly, kicking it a few inches back"
  puts "3. Right, Left, Right and Right"
  puts "Upper Body"
  puts "Bob the Reins"
  puts "1. Holding your arms out in front of you, straight and at chest level"
  puts "2. Cross your right wrist over your left and hold them together"
  puts "3. Lift your arms up and down in a loose bouncing movement, in time with the beat of the song. This movement is repeated eight times"

puts "Lasso"
puts "1. Start arm movement by holding left arm so the back of your wrist is near your chin, pointing your left elbow straight left"
puts "2. Lift right arm up and point right elbow diagonally to the right"
puts "3. Raise right forearm so that it points straight up, and whip it in small circles to the beat of the song, as if you were a cowboy holding a rope lasso"
puts "This movement is repeated eight times as well"
end
Gangnam_Style